language: python
git:
  depth: 3
install:
  - pip install md5checker
script:
  - '[[ "$(md5checker addons.xml)" == "$(cat addons.xml.md5)" ]]'
notifications:
  email: false
branches:
  only:
    - gh-pages
