language: ruby
# install: echo "Install"
script: exit 0
deploy:
  - provider: script
    script: echo "Deploy script"
    skip_cleanup: true
    on:
      branch: master
notifications:
  email: false
branches:
  only:
    - master
